// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIVC_ojlgiFMgV8NH6fxzwzCmRIu7KJkI',
    appId: '1:1069747703790:web:729c34d82e8a6831b8c8ff',
    messagingSenderId: '1069747703790',
    projectId: 'chat-app-e5f75',
    authDomain: 'chat-app-e5f75.firebaseapp.com',
    storageBucket: 'chat-app-e5f75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlM0fpraIOmnMWcKByqGPtDwXm_0ZMERw',
    appId: '1:1069747703790:android:2bbe664bf4ae34a8b8c8ff',
    messagingSenderId: '1069747703790',
    projectId: 'chat-app-e5f75',
    storageBucket: 'chat-app-e5f75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_395DDQRjJdm8qCfNjDuFcNRX0OrhYI0',
    appId: '1:1069747703790:ios:5157817d015dbcdbb8c8ff',
    messagingSenderId: '1069747703790',
    projectId: 'chat-app-e5f75',
    storageBucket: 'chat-app-e5f75.appspot.com',
    iosClientId: '1069747703790-76gdsdm4k4hdtuubieco8hbqr410k1t7.apps.googleusercontent.com',
    iosBundleId: 'com.example.nishthaSaraswatAnswersaiFlutter',
  );
}
